#!/bin/bash
# Enter a chroot environment for Gentoo.
# NOT MINE CREDITS TO THE SONIC MASTER AND MASSOS https://github.com/MassOS-Linux/MassOS
set -e

if [ $EUID -ne 0 ]; then
  echo "Error: gentoo-chroot must be run as root." >&2
  exit 1
fi

chrootdir="$1"
shift

if [ -z "$chrootdir" ]; then
  echo "Usage: gentoo-chroot <chroot dir> [optional custom command]"
  exit 1
fi

if [ ! -d "$chrootdir" ]; then
  echo "Error: $chrootdir is not a directory I can chroot into." >&2
  exit 1
fi

echo "Entering chroot environment in $chrootdir..."

cp --dereference /etc/resolv.conf "$chrootdir"/etc
mount --types proc /proc "$chrootdir"/proc 
mount --rbind /sys "$chrootdir"/sys 
mount --make-rslave "$chrootdir"/sys 
mount --rbind /dev "$chrootdir"/dev 
mount --make-rslave "$chrootdir"/dev 
mount --bind /run "$chrootdir"/run 
mount --make-slave "$chrootdir"/run 

set +e

chroot "$chrootdir" "$@"
STATUS=$?

set -e

echo "Exiting chroot environment..."

sync
umount -l "$chrootdir"/dev{/shm,/pts,}
umount -R "$chrootdir"

if [ $STATUS -eq 0 ]; then
  echo "Chroot exited successfully."
else
  echo "Chroot exited with unsuccessful exit code $STATUS."
fi

exit $STATUS
